### ISSUE TITLE
Question - How to read example "disable all swords" exactly

### ISSUE THREAD

**Issue by wantedkeks** [nvb-uy/Item_Obliterator#85]
Hej there,

I just discovered that fancy mod.
In general, I dont have major problems to use it disabling specific items or a group of items.

I wonder how to read the given example "!minecraft:.*_sword"
"" = that is one entry
minecraft = modid
_sword = end of item id

What tasks do the other tiles have?
! is telling what?
.* says what?

Firstly I am curious to read the code right.
In addition, I am also looking for how to blacklist yellow stuff or all "stained" (glass) as example.
"!minecraft:.*yellow%", 
"!minecraft:.*stained%"
% = dont know how to fill the line correctly.

Thanks!

**Comment by nvb-uy** [comment]
Please search about Regular Expressions (regex) in Google. This isn’t exactly something from Item Obliterator, it’s a standard way of matching strings

**Comment by wantedkeks** [comment]
Thanks for the keyword, that helped!
"!minecraft:.*stained.*" now blacklists every stained (glass) stuff.

/closed

**Comment by pedro9006** [comment]
<img width="423" height="143" alt="Image" src="https://github.com/user-attachments/assets/35c1cdcb-42fe-42e1-b82d-67ba53b122e3" />


Weird. I've been trying to do this for around 30 minutes, and yet the example isn't working.
Even inputting `"!minecraft:.*stained.*"` as said in the post above doesn't work.

<img width="524" height="254" alt="Image" src="https://github.com/user-attachments/assets/f52d7ab0-5dfd-4e3c-b046-bd46501eea9f" />

Any help on this would be appreciated

**Comment by wantedkeks** [comment]
dont know if i can help, how is your config file looking?

**Comment by pedro9006** [comment]
The config file works perfectly fine as of now, albeit _very_ cluttered due to the amount of items removed, but attempting to do anything involving regex just doesn't work. I did see another issue later on that talked about this, so i'm inclined to believe that it's likely not a fault of mine when it comes to formatting.

<img width="927" height="883" alt="Image" src="https://github.com/user-attachments/assets/4e40ba5d-41d3-4849-b0c8-813c84448a0a" />

<img width="618" height="808" alt="Image" src="https://github.com/user-attachments/assets/c381c923-b94f-49f6-8c8b-29d54630f4ed" />

<img width="527" height="695" alt="Image" src="https://github.com/user-attachments/assets/f5db9ca9-9762-40b6-ab10-8c92033fd566" />

<img width="1278" height="666" alt="Image" src="https://github.com/user-attachments/assets/07c0ec9c-08ea-4a8c-8c6d-50dabe415119" />

<img width="1186" height="212" alt="Image" src="https://github.com/user-attachments/assets/a10b6c10-0d2e-4c5c-bbfe-20bd2a5650cf" />

If regex really isn't working anymore then there's simply nothing I can do at the moment until the mod gets updated to fix that, but in either scenario I appreciate the response!

**Comment by maevius669** [comment]
@pedro9006  it's right there in the comments for `use_hashmap_optimizations`,
if it's `true` then regex will NOT work.
